### ISSUE TITLE
Where can I find the documentation for this client ?

### ISSUE THREAD

**Issue by gerazenobi** [elastic/enterprise-search-js#11]
Hi there 👋 

I haven't been able to find the documentation to use this client. Any help would be appreciated.

Something similar to this for example : https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/introduction.html

Second question: what is the difference between the client above and this other one in this repo ?

**Comment by raulclaudino** [comment]
@gerazenobi I have the same doubts as you. 
I'm using the test files and PHP version files to better understand how functions in JS work.

https://github.com/elastic/enterprise-search-js/blob/main/packages/enterprise-search/test/integration/app/documents.test.ts

https://github.com/elastic/enterprise-search-php/blob/master/src/AppSearch/Endpoints.php

**Comment by gerazenobi** [comment]
@raulclaudino thanks :) 

I'll start by that in the meantime !

**Comment by ZakKa89** [comment]
Also wondering about this. The type definitions are incomplete so I have no idea for example how to add a filter to a search.

**Comment by staminna** [comment]
How can I generate a token?  I haven't found a way to generate the Bearer token and I can't authenticate with only the user and pass. I am using the trial version. If it won't work I'll have to find another solution:


Although I have it on my dev machine. I have the client ID, secret, user, pass, and hostname in AWS. I guess I must have a Bearer token as well but I can't find it on the production server.

**Comment by chriscressman** [comment]
> I haven't been able to find the documentation to use this client. Any help would be appreciated.

Elastic recently promoted this client from beta to generally available. Documentation is now available on the Elastic website:

https://www.elastic.co/guide/en/enterprise-search-clients/enterprise-search-node/current/index.html

Sorry for the delay!

**Comment by chriscressman** [comment]
> How can I generate a token?

You can create an API key within Kibana:

| If you need a key for a ... | Go here in Kibana ... |
| --- | --- |
| App Search engine | Enterprise Search > App Search > Credentials |
| Workplace Search content source | Enterprise Search > Workplace Search > API keys |
| Elasticsearch index | Stack Management > API keys > Create |

**Comment by staminna** [comment]
@chriscressman 

Sorry to add no closed issue, I am quite sure my credentials look very similar to the example configuration:
This is meant to work on the node.js elastic enterprise search npm module:
(These credentials are not real, but similar to the example and my own)

```
const { Client } = require('@elastic/enterprise-search');

const client = new Client({
  url: 'https://my-deployment-124322.ent.eu-west-3.aws.elastic-cloud.com',
  auth: {
    token: 'private-6khjfgd2ft9s72vsj7kqtd3ygz'
  }
})

async function run() {
  const health = await client.enterprise.getHealth()
  if (health.errors) {
    console.log(health)
    return
  }
  console.log(health)
}

run().catch(console.error)

async function Search() {
  const searchResponse = await client.app.search(
    { engine_name: 'search-tretas',
        body: {query: 'emprego 2023'}})
    if (searchResponse.errors) {
      console.log(searchResponse)
      process.exit(1)
    }
  console.log(searchResponse)
}

Search().catch(console.error)

```

 ResponseError: {"error":"unable_to_authenticate_user"}

**Comment by chriscressman** [comment]
@staminna Unfortunately, the two APIs you are using above manage access differently. You'd have to use two different instances of the client to access them.

It looks like you have the correct API key for the App Search API.

Access for the health API is documented here: https://www.elastic.co/guide/en/enterprise-search/current/monitoring-apis.html#monitoring-apis-auth (you can use the username/password for a deployment superuser)

**Comment by staminna** [comment]
It's not about the monitoring but I am quite sure I am using the right credentials.
I think I don't need two different instances of the client, so I removed the non-enterprise one.
I just need to access the information I installed to enterprise-search from elastic on my machine, on localhost. Do you think this may be a problem like a router port, cors, or firewall? I think this should just work as per the docs.

This is all that I am using but the issue remains the same:

`const { Client } = require('@elastic/enterprise-search');

const client = new Client({
  url: 'https://my-deployment-124322.ent.eu-west-3.aws.elastic-cloud.com',
  auth: {
    token: 'private-6khjfgd2ft9s72vsj7kqtd3ygz'
  }
})`

ResponseError: {"error":"unable_to_authenticate_user"}

**Comment by chriscressman** [comment]
@staminna I don't see any issues with the way you are initializing the client. I suggest asking about your issue more broadly here:

https://discuss.elastic.co/c/enterprise-search

Your issue is likely not related to the JavaScript client.
