### ISSUE TITLE
Which client to use ?

### ISSUE THREAD

**Issue by gerazenobi** [elastic/enterprise-search-js#14]
Hi there 👋 

Given this client https://github.com/elastic/app-search-node is deprecated and both of the clients here: https://github.com/elastic/enterprise-search-js are in beta or not released yet and don't have comprehensive documentation:

- Which client are we supposed to use on our backend to manage our engines, generate signed keys, CRUD documents ?
- Which client are we supposed to use on our front end to perform searches ?

Thanks in advance.

**Comment by gerazenobi** [comment]
@leemthompo I saw you were the last to commit in this repo, would you be able to help me out with this question ? Thanks in advance 🙏

**Comment by leemthompo** [comment]
👋 I think @ezimuel or @picandocodigo should be able to answer this.

**Comment by ezimuel** [comment]
@gerazenobi The stable Enterprise Search clients including the support of App Search and Workplace Search are:
- [elastic/enterprise-search-python](https://github.com/elastic/enterprise-search-python)
- [elastic/enterprise-search-ruby](https://github.com/elastic/enterprise-search-ruby)
- [elastic/enterprise-search-php](https://github.com/elastic/enterprise-search-php)

The Javascript client is still in beta and we don't have a date release yet. I'll update you when we will have some news in that regard. Thanks.

**Comment by gerazenobi** [comment]
@ezimuel thanks for the answer. 

Until then, what would be your recommendation: 
- hitting the REST API directly without a client
- using this beta client
- using the [deprecated client](https://github.com/elastic/app-search-node)

**Comment by gerazenobi** [comment]
@ezimuel

>I would use this hard way option only if the client doesn't support some specific API yet.

Do you know if this client is going to support [generating signed search keys](https://www.elastic.co/blog/personalizing-content-with-signed-search-keys-in-elastic-app-search) soon ?

Thanks in advance.
