### ISSUE TITLE
`app.multiSearch` is missing on 8.6.0 but in main & docs

### ISSUE THREAD

**Issue by florent-andre** [elastic/enterprise-search-js#38]
Hi there, 
During playing with this lib in 8.6.0 I raised a `TypeError: client.app.multiSearch is not a function`.

## 🐛 Bug Report

* The multiSearch function exist in the [main branch](https://github.com/elastic/enterprise-search-js/blob/main/packages/enterprise-search/src/api/app/api.ts#L964) 
* But disappear from the [8.6.0 branch](https://github.com/elastic/enterprise-search-js/blob/v8.6.0/packages/enterprise-search/src/api/app/api.ts#L963). 

Is this intended ? Easy to get back in the package ?

Thanks you for this useful tool !

**Comment by JoshMock** [comment]
This was fixed in [8.6.1](https://github.com/elastic/enterprise-search-js/releases/tag/v8.6.1), released to npm yesterday.
