### ISSUE TITLE
app.putSchema() schema param types do not match the documentation 

### ISSUE THREAD

**Issue by C3nE3s** [elastic/enterprise-search-js#41]
## 🐛 Bug Report

The provided typescript types for the schema property in the params object for `client.app.putSchema()` do not match the example provided in the [documentation](https://www.elastic.co/guide/en/enterprise-search-clients/enterprise-search-node/master/app-search-api.html#app-search-api-schema-apis-update).

## To Reproduce
```ts
async function run () {
  const schemaUpdate = await client.app.putSchema(
    {engine_name: 'national-parks',
    schema: {date_established: 'date'}})
  if (schemaUpdate.errors) {
    console.log(schemaUpdate)
    process.exit(1)
  }
  console.log(schemaUpdate)}

run().catch(console.error)
```

## Expected behavior

The provided type for the param property schema is as follows:
```ts
schema?:  {
        [k: string]: {
            [k: string]: unknown;
        };
    };
```
This requires nested object structure while the documentation demonstrates a flat object. I assume this typing is off, but if not, I would expect the example to reflect why the schema object shape is something other than a 
`Record<string,unknown>`

- *node version*: 18.14.2
- `@elastic/enterprise-search` *version*: 8.6.0
- *os*: Mac
- *typescript version*: 4.7.4

**Comment by ricokareem** [comment]
@TattdCodeMonkey @delvedor @leemthompo I know this is **_really low-hanging fruit_**, but just bumping the above PR, unless you see this as a breaking change.
Thanks in advance.

**Comment by TattdCodeMonkey** [comment]
@ricokareem sorry for the late response.

This client is generated from an OpenAPI spec and it appears this type is not being generated correctly based on that spec. I will investigate that and see if I can resolve this in the next release.
