### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by jenseo** [elastic/enterprise-search-js#49]
## 💬 Questions and Help

Hello, is this package maintained or do you advise enterprise app search users to use another client? It seems you are not responding to the issues raised and since the version is behind of the official elasticsearch version, mismatches occur that blocks us from using it.

There are so many different clients from elastic to choose from and it has made it hard for us to navigate to which one is the correct one we should use in our case (enterprise app search in NodeJS). 

Thanks, hope to get a reply!

**Comment by cosieLq** [comment]
I have the same question and hope that someone from the team will respond soon!

**Comment by JoshMock** [comment]
This package has fallen out of maintenance, but will bounce back soon. I'm the maintainer of elasticsearch-js as of a few months ago, and have had this project on my to-do list for a while, but other priorities have superseded getting to it. Hoping that changes soon, and I see that @TattdCodeMonkey may have already started prepping for an 8.11 release. :slightly_smiling_face:
